date.timezone = UTC
display_errors = Off
log_errors = On
error_log = /dev/stderr
memory_limit = 256M
max_execution_time = 30

; OPcache
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 0
opcache.enable_cli = 0
